USE backup_sqlife_1;

DELETE FROM contact_1; 
DELETE FROM address_1;
DELETE FROM spending_1;
DELETE FROM users_1;
DELETE FROM cooking_1;
DELETE FROM food_1;
DELETE FROM show_watched_1;
DELETE FROM person_1;
DELETE FROM table_tracker_1;
DELETE FROM my_notes_1;
DELETE FROM natural_medicines_1;
DELETE FROM application_1;
DELETE FROM visit_1;
DELETE FROM job_page_1;
DELETE FROM company_1;
DELETE FROM reading_1;
DELETE FROM book_1;
DELETE FROM secret_1;
DELETE FROM organization_1;
DELETE FROM mother_father_1;
DELETE FROM marriage_1;
DELETE FROM follow_up_1;

INSERT INTO contact_1(SELECT * FROM contact);
INSERT INTO address_1(SELECT * FROM address);
INSERT INTO spending_1(SELECT * FROM spending);
INSERT INTO users_1(SELECT * FROM users);
INSERT INTO cooking_1(SELECT * FROM cooking);
INSERT INTO food_1(SELECT * FROM food);
INSERT INTO show_watched_1(SELECT * FROM show_watched);
INSERT INTO person_1(SELECT * FROM person);
INSERT INTO table_tracker_1(SELECT * FROM table_tracker);
INSERT INTO my_notes_1(SELECT * FROM my_notes);
INSERT INTO natural_medicines_1(SELECT * FROM natural_medicines);
INSERT INTO application_1(SELECT * FROM application);
INSERT INTO visit_1(SELECT * FROM visit);
INSERT INTO job_page_1(SELECT * FROM job_page);
INSERT INTO company_1(SELECT * FROM company);
INSERT INTO reading_1(SELECT * FROM reading);
INSERT INTO book_1(SELECT * FROM book);
INSERT INTO secret_1(SELECT * FROM secret);
INSERT INTO organization_1(SELECT * FROM organization);
INSERT INTO mother_father_1(SELECT * FROM mother_father);
INSERT INTO marriage_1(SELECT * FROM marriage);
INSERT INTO follow_up_1(SELECT * FROM follow_up);


DELETE FROM contact; 
DELETE FROM address;
DELETE FROM spending;
DELETE FROM users;
DELETE FROM cooking;
DELETE FROM food;
DELETE FROM show_watched;
DELETE FROM person;
DELETE FROM table_tracker;
DELETE FROM my_notes;
DELETE FROM natural_medicines;
DELETE FROM application;
DELETE FROM visit;
DELETE FROM job_page;
DELETE FROM company;
DELETE FROM reading;
DELETE FROM book;
DELETE FROM secret;
DELETE FROM organization;
DELETE FROM mother_father;
DELETE FROM marriage;
DELETE FROM follow_up;

INSERT INTO contact(SELECT * FROM sqlife_1.contact);
INSERT INTO address(SELECT * FROM sqlife_1.address);
INSERT INTO spending(SELECT * FROM sqlife_1.spending);
INSERT INTO users(SELECT * FROM sqlife_1.users);
INSERT INTO cooking(SELECT * FROM sqlife_1.cooking);
INSERT INTO food(SELECT * FROM sqlife_1.food);
INSERT INTO show_watched(SELECT * FROM sqlife_1.show_watched);
INSERT INTO person(SELECT * FROM sqlife_1.person);
INSERT INTO table_tracker(SELECT * FROM sqlife_1.table_tracker);
INSERT INTO my_notes(SELECT * FROM sqlife_1.my_notes);
INSERT INTO natural_medicines(SELECT * FROM sqlife_1.natural_medicines);
INSERT INTO application(SELECT * FROM sqlife_1.application);
INSERT INTO visit(SELECT * FROM sqlife_1.visit);
INSERT INTO job_page(SELECT * FROM sqlife_1.job_page);
INSERT INTO company(SELECT * FROM sqlife_1.company);
INSERT INTO book(SELECT * FROM sqlife_1.book);
INSERT INTO reading(SELECT * FROM sqlife_1.reading);
INSERT INTO secret(SELECT * FROM sqlife_1.secret);
INSERT INTO organization(SELECT * FROM sqlife_1.organization);
INSERT INTO mother_father(SELECT * FROM sqlife_1.mother_father);
INSERT INTO marriage(SELECT * FROM sqlife_1.marriage);
INSERT INTO follow_up(SELECT * FROM sqlife_1.follow_up);

